export const fakeUser = [
  {
    gender: "female",
    name: { title: "Ms", first: "Harriet", last: "Clarke" },
    email: "harriet.clarke@example.com",
    id: { name: "", value: null },
    picture: {
      large: "https://randomuser.me/api/portraits/women/85.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/85.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/85.jpg",
    },
    nat: "NZ",
  },
  {
    gender: "male",
    name: { title: "Mr", first: "Krishna", last: "Gamskar" },
    email: "krishna.gamskar@example.com",
    id: { name: "UIDAI", value: "496309759827" },
    picture: {
      large: "https://randomuser.me/api/portraits/men/15.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/15.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/15.jpg",
    },
    nat: "IN",
  },
  {
    gender: "male",
    name: { title: "Mr", first: "Liam", last: "Miles" },
    email: "liam.miles@example.com",
    id: { name: "TFN", value: "944914223" },
    picture: {
      large: "https://randomuser.me/api/portraits/men/53.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/53.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/53.jpg",
    },
    nat: "AU",
  },
  {
    gender: "female",
    name: { title: "Mrs", first: "Lyubanya", last: "Tishik" },
    email: "lyubanya.tishik@example.com",
    id: { name: "", value: null },
    picture: {
      large: "https://randomuser.me/api/portraits/women/50.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/50.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/50.jpg",
    },
    nat: "UA",
  },
  {
    gender: "female",
    name: { title: "Ms", first: "Valentina", last: "Blishchik" },
    email: "valentina.blishchik@example.com",
    id: { name: "", value: null },
    picture: {
      large: "https://randomuser.me/api/portraits/women/5.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/5.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/5.jpg",
    },
    nat: "UA",
  },
  {
    gender: "female",
    name: { title: "Ms", first: "Candela", last: "da Cunha" },
    email: "candela.dacunha@example.com",
    id: { name: "CPF", value: "211.577.528-86" },
    picture: {
      large: "https://randomuser.me/api/portraits/women/45.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/45.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/45.jpg",
    },
    nat: "BR",
  },
  {
    gender: "female",
    name: { title: "Ms", first: "Vladana", last: "Šarić" },
    email: "vladana.saric@example.com",
    id: { name: "SID", value: "520934113" },
    picture: {
      large: "https://randomuser.me/api/portraits/women/73.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/73.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/73.jpg",
    },
    nat: "RS",
  },
  {
    gender: "female",
    name: { title: "Miss", first: "Dora", last: "Rocha" },
    email: "dora.rocha@example.com",
    id: { name: "CPF", value: "942.898.525-10" },
    picture: {
      large: "https://randomuser.me/api/portraits/women/7.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/7.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/7.jpg",
    },
    nat: "BR",
  },
  {
    gender: "female",
    name: { title: "Ms", first: "Weronika", last: "Honningsvåg" },
    email: "weronika.honningsvag@example.com",
    id: { name: "FN", value: "09068435622" },
    picture: {
      large: "https://randomuser.me/api/portraits/women/6.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/6.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/6.jpg",
    },
    nat: "NO",
  },
  {
    gender: "female",
    name: { title: "Miss", first: "Seleni", last: "Gomes" },
    email: "seleni.gomes@example.com",
    id: { name: "CPF", value: "728.275.212-02" },
    picture: {
      large: "https://randomuser.me/api/portraits/women/56.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/56.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/56.jpg",
    },
    nat: "BR",
  },
];
